### ISSUE TITLE
Command `hydra-submitit-launch` not found

### ISSUE THREAD

**Issue by laetitia-teo** [zaccharieramzi/jz-hydra-submitit-launcher#7]
Hi, and thanks for this package.

After installing it (both via pip and after cloning the repo) and trying to run it on JZ I see the following error:
`-bash: hydra-submitit-launch: command not found`

I tried grepping something looking like the command by doing:
`compgen -c | grep hydra`
but I get no result.

**Comment by zaccharieramzi** [comment]
Hi !!

Thanks for your interest and trying to use this!
I am going to take a look into this : it should work!
When you have time, could you copy paste the exact sequence of commands you used before getting the error (with pip)?

**Comment by laetitia-teo** [comment]
```bash
pip install jz-hydra-submitit-launcher
hydra-submitit-launch explore/test_submitit_jz.py
```

**Comment by zaccharieramzi** [comment]
So when I do the following:

```
module load pytorch-gpu/py3/1.9.0
pip install --user jz-hydra-submitit-launcher
hydra-submitit-launch --help
```

I don't have any error, and `pytorch-gpu/py3/1.9.0` is a module I had never used. Could you check that on a fresh connexion to Jean Zay, this sequence of commands does not lead to any error?

If so, then it means that you are probably in some sort of environment that does not let you install the binary.
It might also be that it's because you don't specify `--user`, but I also tried without and it worked.
In which environment are you trying to install the package?

**Comment by zaccharieramzi** [comment]
Hi @laetitia-teo ,

Did you manage to solve this issue?

**Comment by zaccharieramzi** [comment]
Hi @laetitia-teo ,

I am closing this because I assume you managed to solve the issue, but don't hesitate to re-open it if not the case.

**Comment by zaccharieramzi** [comment]
Hi @laetitia-teo ,

Turns out one of my colleagues had the same issue of command not found.
I specified what needs to be done in the readme : https://github.com/zaccharieramzi/jz-hydra-submitit-launcher/commit/1deea42e9d06555d5ec9753040ce281798fc7063

The key point is that the binaries are installed in your local bin, not in your general bin, so you need to put your local binaries in your path. I explain all that in the [readme](https://github.com/zaccharieramzi/jz-hydra-submitit-launcher#install) now, so it should be pretty straightforward, please let me know if it helps.
